FROM gradle:jdk11 as build_image
LABEL maintainer='ai-engineering'

ENV APP_HOME /app
WORKDIR $APP_HOME

# COPY dependencies

COPY build.gradle.kts $APP_HOME
COPY settings.gradle.kts $APP_HOME
COPY src $APP_HOME/src
ADD entrypoint.sh .



# Build
RUN gradle clean build -x test -x ktlintCheck

# Final Docker Image
FROM hub.talkdeskapp.com/talkdesk/base/temurinjdk:11-231219-jre
LABEL maintainer='ai-engineering'

WORKDIR /app

COPY --from=build_image /app/entrypoint.sh /app/
COPY --from=build_image /app/build/libs/*.jar /app/

COPY gradlew /app
