{
 "title": "Project dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(process_cpu_usage, instance)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Instance Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "System CPU usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "system_cpu_usage{instance=~\"$instance\"} * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM CPU usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "process_cpu_usage{instance=~\"$instance\"} * 100",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "JVM Heap usage by instance",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "sum(jvm_memory_used_bytes{area=\"heap\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Memory Used - {{ instance }}"
    },
    {
     "expr": "sum(jvm_memory_committed_bytes{area=\"heap\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Memory Committed - {{ instance }}"
    },
    {
     "expr": "sum(jvm_memory_max_bytes{area=\"heap\",instance=~\"$instance\"}) by (instance)",
     "legendFormat": "Memory Limit - {{ instance }}"
    }
   ]
  }
 ]
}